name: Evolution Engine

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  evolve:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install numpy pillow

      - name: Run evolution
        run: |
          python organism.py

      - name: Commit art
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add art/*.png
          git add history.json

          git commit -m "auto evolution generation" || echo "nothing to commit"

          git pull --rebase
          git push
